const projects = [
  {
    slug: 'green-park-hotel',
    title: 'Грин Парк Отель',
    meta: 'Екатеринбург · редизайн интерьеров · реализация под ключ',
    image: 'https://i.imgur.com/2bG15ls.jpg',
    mobileImage: 'https://i.imgur.com/sKGXO5r.jpg',
    alt: 'Интерьер гостиницы Грин Парк Отель после редизайна',
    wide: true,
    description: 'Редизайн интерьеров гостиницы «Грин Парк Отель» — масштабный проект, в котором мы обновили общественные зоны и номера, сохранив узнаваемый характер отеля. Новая концепция строится на натуральной палитре, тактильных материалах и продуманном свете. Номера отеля получили обновлённую мебель, текстиль и декор, стали спокойнее и уютнее. Интерес посетителей к отелю вырос после редизайна.',
    gallery: [
      'https://i.imgur.com/2bG15ls.jpg',
      'https://i.imgur.com/5umNaYb.jpg',
      'https://i.imgur.com/bXlZYAx.jpg',
      'https://i.imgur.com/sKGXO5r.jpg',
      'https://i.imgur.com/uHZaho1.jpg',
      'https://i.imgur.com/1W9Z4Nb.jpg',
      'https://i.imgur.com/V6s8bZ1.jpg',
      'https://i.imgur.com/1nafpMp.jpg',
      'https://i.imgur.com/o1OMoRe.jpg',
    ],
  },
  {
    slug: 'clever-park',
    title: 'Clever park',
    meta: '160 м² · Екатеринбург · реализация под ключ',
    image: 'https://i.imgur.com/j08o0vm.jpg',
    mobileImage: 'https://i.imgur.com/VvgJm2a.jpg',
    alt: 'Современная кухня с деревянными фасадами, каменным островом и латунными деталями',
    wide: true,
    description: 'Просторная квартира в Clever park для молодой семьи — лаконичный, функциональный интерьер с акцентом на текстуры и свет. Кухня-гостиная с каменным островом стала сердцем дома: здесь готовят, принимают гостей и проводят вечера. Офис, выделенный под отдельную комнату, получился одновременно строгим и уютным за счёт внедрения элементов арт-деко в проект. Помимо этого, здесь полностью было реализовано оснащение квартиры не только мебелью и бытовой техникой, но и электроникой, как, например, сделанный в корпусе стола рабочий ПК с водяным охлаждением. Проект оснащен современной системой умного дома и  реализован под ключ — от первой идеи до финального предмета декора.',
    gallery: [
      'https://i.imgur.com/j08o0vm.jpg',
      'https://i.imgur.com/VvgJm2a.jpg',
      'https://i.imgur.com/gCTHHsi.jpg',
      'https://i.imgur.com/WrIqPV5.jpg',
      'https://i.imgur.com/SsNHMpi.jpg',
      'https://i.imgur.com/1eciPYX.jpg',
      'https://i.imgur.com/mpvmVsP.jpg',
      'https://i.imgur.com/UaF5vSe.jpg',
      'https://i.imgur.com/D9MTkSh.jpg',
      'https://i.imgur.com/sfT0Moc.jpg',
      'https://i.imgur.com/qRCGGdS.jpg',
      'https://i.imgur.com/Jatn2HT.jpg',
      'https://i.imgur.com/iP4nscm.jpg',
      'https://i.imgur.com/2a5gbfE.jpg',
      'https://i.imgur.com/EG1kM6e.jpg',
      'https://i.imgur.com/FFBmYfd.jpg',
      'https://i.imgur.com/p8XpLjy.jpg',
      'https://i.imgur.com/SZWQotb.jpg',
    ],
  },
  {
    slug: 'zhk-kandinskiy',
    title: 'ЖК «Кандинский»',
    meta: '95 м² · Екатеринбург · реализация под ключ',
    image: 'https://i.imgur.com/xHL5Yxh.jpg',
    alt: 'Интерьер квартиры в ЖК Кандинский',
    wide: false,
    objectPosition: 'center',
    description: 'Квартира в жилом комплексе «Кандинский» — проект, где классические идеи встречаются с современным комфортом. Натуральные материалы создают тёплую, камерную атмосферу, а скрытые системы хранения и инженерные решения обеспечили безупречный порядок. Помимо этого квартира оснащена системой умного дома с полной автоматизацией всего - от климата с влажностью и температурой, до домашнего кинотеатра и поднятия штор утром при пробуждении.',
    gallery: [
      'https://i.imgur.com/xHL5Yxh.jpg',
      'https://i.imgur.com/5MtX7R4.jpg',
      'https://i.imgur.com/mzX88hd.jpg',
      'https://i.imgur.com/zHjmCQr.jpg',
      'https://i.imgur.com/n1coAaR.jpg',
      'https://i.imgur.com/A63h0a7.jpg',
      'https://i.imgur.com/KVVTWpV.jpg',
      'https://i.imgur.com/lQhitCa.jpg',
      'https://i.imgur.com/OTPRdwX.jpg',
      'https://i.imgur.com/RWckE9F.jpg',
      'https://i.imgur.com/gvFFZl7.jpg',
      'https://i.imgur.com/XF1eeqV.jpg',
      'https://i.imgur.com/P9evHru.jpg',
      'https://i.imgur.com/rNAOy7s.jpg',
      'https://i.imgur.com/1jITJ9V.jpg',
      'https://i.imgur.com/bFXMVyE.jpg',
    ],
  },
  {
    slug: 'office-nefteyugansk',
    title: 'Здание АБК лесоперерабаты\u00ADвающего комбината',
    meta: 'Советский · административно-бытовой комплекс · реализация под ключ',
    image: 'https://media.base44.com/images/public/6a25b90cc69d8cc1446d8488/7f7232a54_2.jpg',
    mobileImage: 'https://media.base44.com/images/public/6a25b90cc69d8cc1446d8488/7f7232a54_2.jpg',
    alt: 'Здание административно-бытового комбината лесоперерабатывающего комбината в Советском',
    wide: false,
    description: 'Здание АБК лесоперерабатывающего комбината в ХМАО — масштабный проект, подразумевающий полное обновление здания, от усиления силового каркаса здания и изменения фасадов до интерьеров помещений вместе со всеми инженерными коммуникациями. Нашей задачей было создать функциональное и современное пространство, отражающее характер предприятия: открытые рабочие зоны, офисные помещения с акцентом на древесные фактуры и продуманную навигацию. Современные материалы и проектные решения подчёркивают промышленную эстетику и делают здание комфортным для сотрудников. В портфолио проекта представлены некоторые фотографии проекта до и в процессе реконструкции, а также пример 3D-визуализации одного из офисов.',
    gallery: [
      'https://media.base44.com/images/public/6a25b90cc69d8cc1446d8488/8c9d5161f_0.jpg',
      'https://media.base44.com/images/public/6a25b90cc69d8cc1446d8488/ce1a1cea3_1.jpg',
      'https://media.base44.com/images/public/6a25b90cc69d8cc1446d8488/7f7232a54_2.jpg',
      'https://media.base44.com/images/public/6a25b90cc69d8cc1446d8488/681830cc2_3.jpg',
      'https://media.base44.com/images/public/6a25b90cc69d8cc1446d8488/8f365586e_4.jpg',
      'https://media.base44.com/images/public/6a25b90cc69d8cc1446d8488/83e4f48bc_5.jpg',
      'https://media.base44.com/images/public/6a25b90cc69d8cc1446d8488/d2de7f91f_6.jpg',
    ],
  },
  {
    slug: 'dom-italian-provence',
    title: 'Дом в стиле Итальянский прованс',
    meta: '450 м² · Свердловская область · реализация под ключ',
    image: 'https://i.imgur.com/kUyoVm8.jpg',
    mobileImage: 'https://i.imgur.com/XSIouMz.jpg',
    alt: 'Частный дом в стиле Итальянский прованс в Свердловской области',
    wide: false,
    description: 'Дом в стиле Итальянский прованс — проект, в котором мы воплотили мечту о загородной жизни с южноевропейским колоритом. Тёплые терракотовые оттенки, натуральный камень, штукатурка и дерево создают атмосферу итальянской виллы. Просторные террасы, внутренний дворик с фонтаном и панорамные окна связывают интерьер с природой. Проект реализован под ключ — от архитектурной концепции до ландшафтного дизайна.',
    gallery: [
      'https://i.imgur.com/kUyoVm8.jpg',
      'https://i.imgur.com/uwnltPU.jpg',
      'https://i.imgur.com/TpXCoHF.jpg',
      'https://i.imgur.com/E6yfrG9.jpg',
      'https://i.imgur.com/LYiDa8B.jpg',
      'https://i.imgur.com/GPz5025.jpg',
      'https://i.imgur.com/91VtsZz.jpg',
      'https://i.imgur.com/XSIouMz.jpg',
      'https://i.imgur.com/naI4uMW.jpg',
      'https://i.imgur.com/6DEwaef.jpg',
    ],
  },
  {
    slug: 'clever-park-95',
    title: 'Clever park',
    meta: '95 м² · Екатеринбург · реализация под ключ',
    image: 'https://i.imgur.com/bTLWeHk.jpg',
    mobileImage: 'https://i.imgur.com/bTLWeHk.jpg',
    alt: 'Современная квартира в Clever park с тёплыми фактурами и продуманным светом',
    wide: false,
    description: 'Квартира в Clever park — лаконичный, функциональный интерьер с акцентом на текстуры и свет. Кухня-гостиная стала сердцем дома: здесь готовят, принимают гостей и проводят вечера. Деревянные фасады, микроцемент и тёплая подсветка создают уют, а продуманная эргономика делает каждый квадратный метр рабочим. Проект реализован под ключ — от первой идеи до финального предмета декора.',
    gallery: [
      'https://i.imgur.com/bTLWeHk.jpg',
      'https://i.imgur.com/kae7C4l.jpg',
      'https://i.imgur.com/ADG6L2W.jpg',
      'https://i.imgur.com/Bew6pnS.jpg',
      'https://i.imgur.com/u3ceTMM.jpg',
      'https://i.imgur.com/0j9yvib.jpg',
      'https://i.imgur.com/JjLVj4j.jpg',
      'https://i.imgur.com/1YZ7JkA.jpg',
      'https://i.imgur.com/oSTUcb6.jpg',
      'https://i.imgur.com/IxtAXlg.jpg',
      'https://i.imgur.com/NUElj1H.jpg',
      'https://i.imgur.com/ef5jx9d.jpg',
      'https://i.imgur.com/RKkpOtL.jpg',
      'https://i.imgur.com/egeQ39S.jpg',
      'https://i.imgur.com/ttSvjFM.jpg',
      'https://i.imgur.com/HsKZtAt.jpg',
      'https://i.imgur.com/mJUxtVN.jpg',
      'https://i.imgur.com/Ah0g0qe.jpg',
      'https://i.imgur.com/QVW28uF.jpg',
      'https://i.imgur.com/qWhUkbb.jpg',
      'https://i.imgur.com/FoqXzUH.jpg',
      'https://i.imgur.com/UjYoMrj.jpg',
      'https://i.imgur.com/oZRSYUK.jpg',
      'https://i.imgur.com/9Pej7VE.jpg',
      'https://i.imgur.com/f2eaIrw.jpg',
      'https://i.imgur.com/Yg2GxJa.jpg',
      'https://i.imgur.com/TOfkyy2.jpg',
      'https://i.imgur.com/Dn6oxZv.jpg',
      'https://i.imgur.com/SYRwGvl.jpg',
    ],
  },
  {
    slug: 'house-sverdlovsk',
    title: 'Частный дом',
    meta: 'п. Заповедник · создание дизайн-проекта',
    image: 'https://i.imgur.com/SI8xdkc.jpg',
    mobileImage: 'https://i.imgur.com/SbhfmiE.jpg',
    alt: 'Частный загородный дом в посёлке Заповедник с панорамными окнами',
    wide: true,
    description: 'Работа по данному проекту предполагала создание дизайн-проекта исходя из пожеланий заказчика для дальнейшей самостоятельной реализации. Панорамные окна связывают интерьер с природой, а натуральные материалы — камень, дерево, керамика — создают ощущение уюта в любую погоду. Мы продумали зонирование для большой семьи: общие пространства для встреч и уютные приватные зоны. Создание дизайн-проекта включило инженерные решения, тёплые полы и продуманный свет для комфорта круглый год.',
    gallery: [
      'https://i.imgur.com/SI8xdkc.jpg',
      'https://i.imgur.com/jxwqdaT.jpg',
      'https://i.imgur.com/bFd3ltx.jpg',
      'https://i.imgur.com/Ah8FBoE.jpg',
      'https://i.imgur.com/2MHwkli.jpg',
      'https://i.imgur.com/fjL9BbS.jpg',
      'https://i.imgur.com/0N5Dkr1.jpg',
      'https://i.imgur.com/vRVTfLf.jpg',
      'https://i.imgur.com/pC2NHBW.jpg',
      'https://i.imgur.com/SbhfmiE.jpg',
      'https://i.imgur.com/zeLnrCv.jpg',
      'https://i.imgur.com/thtY5hJ.jpg',
      'https://i.imgur.com/C7vPkHc.jpg',
      'https://i.imgur.com/UkHRHfC.jpg',
      'https://i.imgur.com/bOVK18N.jpg',
      'https://i.imgur.com/4ISf9um.jpg',
      'https://i.imgur.com/6T83g9T.jpg',
      'https://i.imgur.com/2oFT13y.jpg',
      'https://i.imgur.com/ptymEnz.jpg',
      'https://i.imgur.com/jSNZO4n.jpg',
      'https://i.imgur.com/7DgOBeT.jpg',
      'https://i.imgur.com/crMINbx.jpg',
      'https://i.imgur.com/gOgGyPh.jpg',
      'https://i.imgur.com/t4KYIDe.jpg',
      'https://i.imgur.com/AvtHLA0.jpg',
      'https://i.imgur.com/Xgp4ZoP.jpg',
      'https://i.imgur.com/gunLWPc.jpg',
      'https://i.imgur.com/OodN8Qk.jpg',
      'https://i.imgur.com/GwzpabL.jpg',
      'https://i.imgur.com/Az1mCaj.jpg',
      'https://i.imgur.com/q2jtx8F.jpg',
      'https://i.imgur.com/mswCtXf.jpg',
      'https://i.imgur.com/53tO7ER.jpg',
      'https://i.imgur.com/KWsfnbi.jpg',
      'https://i.imgur.com/TTVFKXd.jpg',
      'https://i.imgur.com/cHnfkP6.jpg',
      'https://i.imgur.com/r0Jb0Kt.jpg',
    ],
  },
  {
    slug: 'dom-palniks',
    title: 'Частный дом',
    meta: 'п. Палникс · проектирование и реализация ландшафтного освещения',
    image: 'https://i.imgur.com/BQKFaMr.jpg',
    mobileImage: 'https://i.imgur.com/BQKFaMr.jpg',
    alt: 'Частный дом в посёлке Палникс с архитектурной подсветкой фасадов',
    wide: false,
    description: 'Это проект, где свет стал главным инструментом для нашей команды. Задача состояла в реконструкции устаревших светильников и областей освещения. Мы спроектировали и реализовали многоуровневую систему ландшафтного освещения: архитектурную подсветку фасадов, сценарии для террасы и сада, акцентный свет на архитектурных деталях и тёплый рассеянный свет в интерьерах. Каждый сценарий настроен под время суток или настроение — от торжественного приёма гостей до тихого семейного вечера.',
    gallery: [
      'https://i.imgur.com/BQKFaMr.jpg',
      'https://i.imgur.com/QEooohI.jpg',
      'https://i.imgur.com/kib8zl2.jpg',
      'https://i.imgur.com/JrnEj4D.jpg',
      'https://i.imgur.com/QLGSnVn.jpg',
      'https://i.imgur.com/krLgUEc.jpg',
      'https://i.imgur.com/w9QWCDl.jpg',
      'https://i.imgur.com/SJuyZV5.jpg',
      'https://i.imgur.com/CMFMROX.jpg',
      'https://i.imgur.com/bQrlLaE.jpg',
      'https://i.imgur.com/MI99u29.jpg',
      'https://i.imgur.com/y90YW4s.jpg',
      'https://i.imgur.com/cX0pCl9.jpg',
      'https://i.imgur.com/xyeE4VJ.jpg',
      'https://i.imgur.com/6nWFabF.jpg',
      'https://i.imgur.com/bicC4Tf.jpg',
    ],
  },
];

export default projects;

// Порядок на home: ЖК Кандинский (узкий), Clever park 160 (широкий), Грин Парк (широкий), АБК (узкий)
export const featuredSlugs = ['zhk-kandinskiy', 'clever-park', 'green-park-hotel', 'office-nefteyugansk'];

export function getProjectBySlug(slug) {
  return projects.find((p) => p.slug === slug);
}