const projects = [
  {
    slug: 'green-park-hotel',
    title: 'Грин Парк Отель',
    meta: 'Екатеринбург · редизайн интерьеров · проектирование мебели · декорирование · технический и авторский надзор',
    detailMeta: 'Екатеринбург · редизайн интерьеров · проектирование мебели · декорирование · реализация под ключ',
    image: 'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/1%20(осн).jpg',
    mobileImage: 'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/4%20(осн%20моб).jpg',
    alt: 'Интерьер гостиницы Грин Парк Отель после редизайна',
    wide: true,
    description: 'Редизайн интерьеров гостиницы «Грин Парк Отель» — масштабный проект, в котором мы обновили общественные зоны и номера, сохранив узнаваемый характер отеля. Новая концепция строится на натуральной палитре, тактильных материалах и продуманном свете. Номера отеля получили обновлённую мебель, текстиль и декор, стали спокойнее и уютнее. Интерес посетителей к отелю вырос после редизайна.',
    gallery: [
      'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/1%20(осн).jpg',
      'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/2.jpg',
      'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/3.jpg',
      'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/4%20(осн%20моб).jpg',
      'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/5.jpg',
      'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/6.jpg',
      'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/7.jpg',
      'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/8.jpg',
      'https://storage.yandexcloud.net/zharptizza/Грин%20Парк%20Отель/9.jpg',
    ],
  },
  {
    slug: 'clever-park',
    title: 'Clever park',
    meta: '160 м² · Екатеринбург · реализация под ключ',
    image: 'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/1%20(осн).jpg',
    mobileImage: 'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/3%20(осн%20моб).jpg',
    alt: 'Современная кухня с деревянными фасадами, каменным островом и латунными деталями',
    wide: true,
    description: 'Просторная квартира в Clever park для молодой семьи — современный лаконичный и функциональный интерьер с элементами ар-деко. Кухня-гостиная с каменным островом стилистически задает основную идею проекта. Кабинет, выделенный в отдельную зону, получился одновременно строгим и уютным. Помимо этого, здесь полностью было реализовано оснащение квартиры не только мебелью и бытовой техникой, но и электроникой, как, например, домашний кинотеатр с системой окружающего звука. Проект оснащен современной системой умного дома и реализован под ключ — от первой идеи до финального предмета декора.',
    gallery: [
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/1%20(осн).jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/2.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/3%20(осн%20моб).jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/4.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/5.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/6.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/7.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/8.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/9.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/10.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/11.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/12.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/13.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/14.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/15.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/16.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%20160%20sq/17.jpg',
    ],
  },
  {
    slug: 'zhk-kandinskiy',
    title: 'ЖК «Кандинский»',
    meta: '95 м² · Екатеринбург · реализация под ключ',
    image: 'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/1%20(осн%20моб%20и%20деск).jpg',
    mobileImage: 'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/1%20(осн%20моб%20и%20деск).jpg',
    alt: 'Интерьер квартиры в ЖК Кандинский',
    wide: false,
    objectPosition: 'center',
    description: 'Квартира в жилом комплексе «Кандинский» — проект, где современные идеи дизайна дополнены максимальным комфортом. Натуральные материалы создают тёплую, камерную атмосферу, а скрытые системы хранения и инженерные решения обеспечивают безупречный порядок и удобство жизни. Помимо этого квартира оснащена системой умного дома с полной автоматизацией всего - от  управления освещением и климатом, с влажностью и температурой, до полноценного домашнего кинотеатра и поднятия штор утром при пробуждении.',
    gallery: [
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/1%20(осн%20моб%20и%20деск).jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/2.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/3.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/4.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/5.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/6.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/7.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/8.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/9.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/10.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/11.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/12.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/13.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/14.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/15.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Кандинский/16.jpg',
    ],
  },
  {
    slug: 'office-nefteyugansk',
    title: 'АБК лесоперерабаты\u00ADвающего комбината',
    meta: 'ХМАО · генпроектирование · функции технического заказчика · авторский надзор',
    detailMeta: 'ХМАО · генпроектирование · авторский надзор',
    image: 'https://storage.yandexcloud.net/zharptizza/АБК/1.jpg',
    mobileImage: 'https://storage.yandexcloud.net/zharptizza/АБК/1.jpg',
    alt: 'Здание административно-бытового комбината лесоперерабатывающего комбината в Советском',
    wide: false,
    description: 'АБК лесоперерабатывающего комбината в ХМАО — масштабный проект, подразумевающий полное обновление здания, от усиления силового каркаса здания и изменения фасадов до интерьеров помещений вместе со всеми инженерными коммуникациями. Нашей задачей было создать функциональное и современное пространство, отражающее характер предприятия: открытые рабочие зоны, офисные помещения с акцентом на древесные фактуры и продуманную навигацию. Современные материалы и проектные решения подчёркивают промышленную эстетику и делают здание комфортным для сотрудников. В портфолио проекта представлены некоторые фотографии проекта до и в процессе реконструкции, а также пример 3D-визуализации одного из офисов.',
    gallery: [
      'https://storage.yandexcloud.net/zharptizza/АБК/1.jpg',
      'https://storage.yandexcloud.net/zharptizza/АБК/2.jpg',
      'https://storage.yandexcloud.net/zharptizza/АБК/3.jpg',
      'https://storage.yandexcloud.net/zharptizza/АБК/4.jpg',
      'https://storage.yandexcloud.net/zharptizza/АБК/5.jpg',
      'https://storage.yandexcloud.net/zharptizza/АБК/6.jpg',
      'https://storage.yandexcloud.net/zharptizza/АБК/7.jpg',
    ],
  },
  {
    slug: 'dom-italian-provence',
    title: 'Дом в стиле Итальянский прованс',
    meta: '450 м² · Свердловская обл. · проектирование · авторский надзор',
    image: 'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/1%20(осн%20деск).jpg',
    mobileImage: 'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/7%20(осн%20моб).jpg',
    alt: 'Частный дом в стиле Итальянский прованс в Свердловской области',
    wide: false,
    description: 'Дом в стиле Итальянский прованс — проект, в котором мы воплотили мечту о загородной жизни с южноевропейским колоритом. Тёплые терракотовые оттенки, натуральный камень, штукатурка и дерево создают атмосферу итальянской виллы. Просторные террасы, внутренний дворик с фонтаном и панорамные окна связывают интерьер с природой.',
    gallery: [
      'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/1%20(осн%20деск).jpg',
      'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/2.jpg',
      'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/3.jpg',
      'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/4.jpg',
      'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/5.jpg',
      'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/6.jpg',
      'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/7%20(осн%20моб).jpg',
      'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/8.jpg',
      'https://storage.yandexcloud.net/zharptizza/Итальянский%20прованс/9.jpg',
    ],
  },
  {
    slug: 'clever-park-95',
    title: 'Clever park',
    meta: '95 м² · Екатеринбург · реализация под ключ',
    image: 'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/1%20(осн%20моб%20и%20деск).jpg',
    mobileImage: 'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/1%20(осн%20моб%20и%20деск).jpg',
    alt: 'Современная квартира в Clever park с тёплыми фактурами и продуманным светом',
    wide: false,
    description: 'Квартира в Clever park — проект, выполненный в стиле «Тихой роскоши». Кухня-гостиная стала сердцем дома — здесь готовят, принимают гостей и проводят вечера. Деревянные фасады, текстильные обои и тёплая комфортная подсветка создают уют, а продуманная эргономика делает каждый квадратный метр удобным. Современные инженерные системы обеспечивают необходимый уровень качества проживания в квартире. Проект реализован под ключ — от первой идеи до финального предмета декора.',
    gallery: [
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/1%20(осн%20моб%20и%20деск).jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/2.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/3.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/4.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/5.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/6.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/7.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/8.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/9.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/10.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/11.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/12.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/13.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/14.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/15.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/16.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/17.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/18.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/19.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/20.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/21.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/22.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/23.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/24.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/25.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/26.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/27.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/28.jpg',
      'https://storage.yandexcloud.net/zharptizza/Clever%20park%2090%20sq/29.jpg',
    ],
  },
  {
    slug: 'house-sverdlovsk',
    title: 'Частный дом',
    meta: 'п. Заповедник · создание дизайн-проекта · авторский надзор',
    image: 'https://storage.yandexcloud.net/zharptizza/Заповедник/1.jpg',
    mobileImage: 'https://storage.yandexcloud.net/zharptizza/Заповедник/8%20(моб%20кухня).jpg',
    alt: 'Частный загородный дом в посёлке Заповедник с панорамными окнами',
    wide: false,
    description: 'Работа по данному проекту предполагала создание дизайн-проекта исходя из пожеланий заказчика для дальнейшей самостоятельной реализации.  Панорамные окна связывают интерьер с природой, а натуральные материалы — камень, дерево, керамика — создают ощущение уюта в любую погоду. Мы продумали зонирование для большой семьи: общие пространства для встреч и уютные приватные зоны. Создание дизайн-проекта включило инженерные решения, тёплые полы и продуманный свет для комфорта круглый год. На фото представлен уже реализованный интерьер.',
    gallery: [
      'https://storage.yandexcloud.net/zharptizza/Заповедник/1.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/2.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/3.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/4.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/5.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/6.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/7.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/8%20(моб%20кухня).jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/9.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/10%20(моб).jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/11.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/12.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/13.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/14.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/15.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/16.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/17.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/18.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/19.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/20.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/21.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/22.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/23.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/24.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/25.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/26.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/27.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/28.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/29.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/30.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/31.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/32.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/33.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/34.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/35.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/36.jpg',
      'https://storage.yandexcloud.net/zharptizza/Заповедник/37.jpg',
    ],
  },
  {
    slug: 'dom-palniks',
    title: 'Частный дом',
    meta: 'п. Палникс · проектирование ландшафтного освещения · авторский надзор',
    image: 'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/1%20(осн%20моб%20и%20деск).jpg',
    mobileImage: 'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/1%20(осн%20моб%20и%20деск).jpg',
    alt: 'Частный дом в посёлке Палникс с архитектурной подсветкой фасадов',
    wide: false,
    description: 'Задача состояла в реконструкции устаревшего уличного освещения дома и придомового участка земли. Мы спроектировали многоуровневую систему ландшафтного освещения — архитектурную подсветку всей территории усадьбы, фасадов дома и лестниц, дорожек, лесной зоны, зоны патио, а также реализовали акцентный свет на растениях и деталях. Все ландрафтное освещение настроено сценариями под время суток.',
    gallery: [
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/1%20(осн%20моб%20и%20деск).jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/2.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/3.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/4.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/5.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/6.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/7.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/8.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/9.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/10.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/11.jpg',
      'https://storage.yandexcloud.net/zharptizza/Палникс%20освещение/12.jpg',
    ],
  },
  {
    slug: 'ekaterininskiy-3d',
    title: 'ЖК Екатерининский парк',
    meta: 'формат PDF · дизайн-проект',
    image: 'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/1%20(осн%20моб%20и%20деск).jpg',
    mobileImage: 'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/1%20(осн%20моб%20и%20деск).jpg',
    alt: '3D-визуализация интерьера квартиры в ЖК Екатерининский',
    wide: false,
    description: 'Квартира в ЖК «Екатерининский парк» для семьи из 5 человек — пример дизайн-проекта без реализации, с подготовкой полного комплекта технической документации. В проекте помимо интерьерных решений, выполненных в виде 3D-визуализации, разработаны планы, развёртки, узлы и спецификации, оформленные в формате PDF. Такой подход показывает, как бюро доводит интерьер до рабочей стадии: от обмеров и планировочных решений до детализации мебели и подбора материалов. Документация подготовлена максимально полно, так, чтобы уменьшить количество вопросов при строительстве.',
    gallery: [
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/1%20(осн%20моб%20и%20деск).jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/2.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/3.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/4.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/5.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/6.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/7.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/8.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/9.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/10.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/11.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/12.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/13.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/14.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/15.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/16.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/17.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/18.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/19.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/20.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/21.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/22.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/23.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/24.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/25.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/26.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/27.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/28.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/29.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/30.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/31.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/32.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/33.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/34.jpg',
      'https://storage.yandexcloud.net/zharptizza/ЖК%20Екатерининский/35.jpg',
    ],
  },
];

export default projects;

// Порядок на home: ЖК Кандинский (узкий), Clever park 160 (широкий), Грин Парк (широкий), Частный дом (широкий)
export const featuredSlugs = ['zhk-kandinskiy', 'clever-park', 'green-park-hotel', 'house-sverdlovsk'];

export function getProjectBySlug(slug) {
  return projects.find((p) => p.slug === slug);
}